language: node_js
sudo: required
cache:
   directories:
     - node_modules
node_js:
  - 8
before_install:
  - npm install
  - npm install -g node-gyp
  - export NODE_ENV=production
script:
  - npm run lint
